# -*- coding: utf-8 -*-
"""add_numbers.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/120tKUGEkQlar0MfmxlE6OeydFYiGtVEs
"""

def add(a,b):
  return a+b

sum = add(12,13)
print(sum)

