# -*- coding: utf-8 -*-
"""greet.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/120tKUGEkQlar0MfmxlE6OeydFYiGtVEs
"""

def greet():
  print("Hiii")
greet()

