# -*- coding: utf-8 -*-
"""multiply.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/120tKUGEkQlar0MfmxlE6OeydFYiGtVEs
"""

def multiply(a,b):
  return a*b
product = multiply(12,15)
print(product)

