# -*- coding: utf-8 -*-
"""subtract.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/120tKUGEkQlar0MfmxlE6OeydFYiGtVEs
"""

def subtract(a,b):
  return a-b
sub = subtract(12,15)
print(sub)

